### ISSUE TITLE
ugrep support.

### ISSUE THREAD

**Issue by hongyi-zhao** [jimporter/urgrep#1]
I've just encountered with [ugrep](https://github.com/Genivia/ugrep) today, which has a wealth of [amazing features](https://github.com/Genivia/ugrep#notable-improvements-over-grep) and [excellent performance](https://github.com/Genivia/ugrep#performance-results), as noted on the project's website. So, I think that it should be a wonderful thing if it can be supported by `urgrep`.

Regards,
HY

**Comment by jimporter** [comment]
Interesting, I hadn't heard of ugrep before either! I'll have to take a look at what all it can do and how best to support that in this package, but it definitely seems like a good fit.

**Comment by jimporter** [comment]
Resolved in f002b3ad781514b036e6cbad2f2150f50c22ab4a. I haven't used ugrep extensively, so hopefully everything works right. I did add unit tests though.
