### ISSUE TITLE
Can't display ansi color on remote file

### ISSUE THREAD

**Issue by lakkiy** [jimporter/urgrep#12]
I run urgrep on remote project that open with tramp, the result looks wired:

![image](https://github.com/jimporter/urgrep/assets/24653356/69419234-5f1c-41dc-8313-cfbae461af10)

**Comment by lakkiy** [comment]
I also try to use rg instead ugrep, don't work too. But rg.el worked.

**Comment by jimporter** [comment]
@mrunhap Could you try the latest development build? (Either from this repo directly or using [GNU-devel ELPA](https://elpa.gnu.org/devel/).) I think I fixed this but just haven't tagged a new release yet...

**Comment by lakkiy** [comment]
> @mrunhap Could you try the latest development build? (Either from this repo directly or using [GNU-devel ELPA](https://elpa.gnu.org/devel/).) I think I fixed this but just haven't tagged a new release yet...

Yes, I use package-vc-install to install urgrep from github and it worked.

**Comment by jimporter** [comment]
Thanks for checking. I've now tagged v0.4.1, so it should hit the (non-devel) GNU ELPA soon. I think it updates every 12 hours, so you should see it there by sometime tomorrow.
