### ISSUE TITLE
Wgrep support

### ISSUE THREAD

**Issue by danielmartin** [jimporter/urgrep#2]
Thank you for working on this package!

For compatibility with the wgrep package (https://github.com/mhayashi1120/Emacs-wgrep), is there a plan to keep the traditional grep-mode output (at least as an option) so that this package can be used in tandem with wgrep in project-wide search and replace operations?

Thanks!

**Comment by jimporter** [comment]
That option should already exist (set [`urgrep-group-matches`](https://github.com/jimporter/urgrep/blob/19b2955da2887c9085f8f4c56b86895f775ea063/urgrep.el#L44-L47) to nil), but what I'd really like to do is to make a new package that depends on both this and wgrep that works with all the various options here. That seems like it should be possible, given that wgrep already has components for ag, ack, etc. I haven't really looked into it yet though...

**Comment by danielmartin** [comment]
Jim Porter ***@***.***> writes:

> That option should already exist (set
> [`urgrep-group-matches`](https://github.com/jimporter/urgrep/blob/19b2955da2887c9085f8f4c56b86895f775ea063/urgrep.el#L44-L47)
> to nil),

Thanks, I missed that option. Works like a charm.

> but what I'd really like to do is to make a new package that
> depends on both this and wgrep that works with all the various options
> here. That seems like it should be possible, given that wgrep already
> has components for ag, ack, etc. I haven't really looked into it yet
> though...

Makes sense, I think it'd be great to teach wgrep how to edit grouped
results from other packages, including xref.

**Comment by jimporter** [comment]
Ok, wgrep *should* work from inside urgrep now. I've only lightly tested it so far[1], but it seems to do the right thing for simple cases at least. I welcome further testing here (and hopefully I'll be able to add some decent automated tests for this in the future).

[1] I haven't used wgrep prior to this, so I may have missed some things.
