### ISSUE TITLE
Eshell integration fails with bad keyword argument

### ISSUE THREAD

**Issue by Stebalien** [jimporter/urgrep#5]
I'm getting the following error:

> Keyword argument /path/to/cwd/ not one of (:tool :regexp :case-fold :files :group :context :color :directory)

It looks like the issue is:

https://github.com/jimporter/urgrep/blob/587494b0ed6a7507379db8ad792afaa0abcbe23a/urgrep.el#L1218

That should probably be passing the directory as an option.

**Comment by jimporter** [comment]
Oops, thanks for the catch. I see a few other issues here too, especially around the "plain" behavior (when `eshell-plain-grep-behavior` is non-nil), so I'll try and get all that fixed and tested.

**Comment by jimporter** [comment]
I've now added some tests, so just as soon as Github Actions are working again (I should really migrate to Sourcehut one of these days...), I'll tag a new release so it gets distributed via GNU ELPA.

**Comment by jimporter** [comment]
> I've now added some tests, so just as soon as Github Actions are working again (I should really migrate to Sourcehut one of these days...), I'll tag a new release so it gets distributed via GNU ELPA.

Now done. Just waiting on GNU ELPA to update.
