### ISSUE TITLE
Expansion of ~ on Windows

### ISSUE THREAD

**Issue by elge70** [jimporter/urgrep#8]
I use project.el to open the project and files. I use ripgrep to search for pattern and it is not working. The project stores the path of project in .emacs.d/projects file as "~/Repo" etc. That could be the problem. This problem is not seen if I am using consult-ripgrep. This can be reproduced with ugrep also.

_Originally posted by @elge70 in https://github.com/jimporter/urgrep/issues/7#issuecomment-1859504008_

**Comment by elge70** [comment]
When using project.el, compile also shows default-directory as "~/xx/yy". I am using emacs 29.1

**Comment by jimporter** [comment]
Please continue the discussion in #7.
