### ISSUE TITLE
Please consider renaming this package (name collision with Genivia/ugrep)

### ISSUE THREAD

**Issue by jasonm23** [jimporter/urgrep#9]
Please note there's a name collision on this package https://github.com/Genivia/ugrep

Please consider changing the name of this package, to allow the Emacs community to find packages and tools relevant to `ugrep` 

Thank you.

**Comment by jimporter** [comment]
There's no collision. While the names are similar looking, this package is named `urgrep` (with 2 Rs), whereas that's `ugrep` (with 1 R).
